# home-manager module: a daily restic backup of $HOME with retrieval
# verification and optional replica repositories, plus sensible excludes
# for macOS junk (caches, Library/Containers, package manager state,
# build artefacts, etc.).
#
# The operational program is ../backup-home.rs, a rust-script. This module
# is only declarative glue: it generates the exclude file, substitutes the
# serialized configuration into the Rust source, pins the rust-script
# interpreter, compiles a small C exec-wrapper that fixes PATH and the
# darwin toolchain environment (same pattern as wallstats), and wires up
# the scheduler.
#
# Two scheduling backends, picked automatically:
#
#   1. systeml (https://github.com/cognivore/systeml) if the user has
#      `systeml.enable = true` in their home configuration. Emits a
#      `systemd.user.{services,timers}.backup-home` pair which the
#      systeml daemon picks up and supervises.
#
#   2. launchd otherwise — emits a `launchd.agents.backup-home` entry
#      with `StartCalendarInterval`.
#
# The user provides only the repository URL and a password-fetch command:
#
#   services.backup-home = {
#     enable = true;
#     repo = "rclone:gdrive:backups/myhost";
#     passwordCommand = "${pkgs.passveil}/bin/passveil show restic/backup";
#     # schedule.hour = 14; schedule.minute = 0;  # defaults
#     # replicaRepos = [ "sftp:user@host:backups/myhost" ];
#   };

{ config, lib, pkgs, ... }:

let
  cfg = config.services.backup-home;
  homeDir = config.home.homeDirectory;
  logDir = "${homeDir}/.local/log";

  excludeFile = pkgs.writeText "restic-home-excludes" (''
    # macOS junk
    ${homeDir}/.Trash
    .DS_Store
    .zcompdump*
    ${homeDir}/.CFUserTextEncoding
    ${homeDir}/.zsh_sessions

    # Caches
    ${homeDir}/.cache
    ${homeDir}/Library/Caches
    ${homeDir}/Library/Logs
    ${homeDir}/Library/HTTPStorages
    ${homeDir}/Library/WebKit

    # Library: large regenerable app data
    ${homeDir}/Library/Developer
    ${homeDir}/Library/Containers/com.utmapp.UTM
    ${homeDir}/Library/Containers/com.docker.docker

    # Apple-shipped sandboxed apps. Their container directories are
    # FDA-locked at the directory level (Mail, Messages, Notes, Safari,
    # Maps, Home, VoiceMemos, …). The data is iCloud-synced or regenerable
    # — restoring from a restic snapshot of these would be incomplete
    # anyway. Exclude the whole namespace.
    ${homeDir}/Library/Containers/com.apple.*
    ${homeDir}/Library/Application Support/Steam
    ${homeDir}/Library/Application Support/Claude
    ${homeDir}/Library/Application Support/Google
    ${homeDir}/Library/Application Support/Godot
    ${homeDir}/Library/Application Support/Adobe
    ${homeDir}/Library/Application Support/Battle.net
    ${homeDir}/Library/Application Support/Spotify
    ${homeDir}/Library/Application Support/Chromium
    ${homeDir}/Library/Application Support/CEF
    ${homeDir}/Library/Application Support/com.openai.atlas
    ${homeDir}/Library/Application Support/TorBrowser-Data
    ${homeDir}/Library/Application Support/Deezer
    ${homeDir}/Library/Application Support/Slack
    ${homeDir}/Library/Application Support/Zulip
    ${homeDir}/Library/Application Support/Superhuman

    # macOS SIP/TCC-protected directories (inaccessible without Full Disk
    # Access). Restic exits 3 when it can't read any source file, so even
    # one of these slipping through promotes the whole run to "failed".
    # These were collected empirically from journalctl -u backup-home.

    # Per-app sandbox metadata plists. macOS protects these on every
    # container (Apple and third-party). They're regenerated by
    # containermanagerd; no value in trying to back them up.
    **/.com.apple.containermanagerd.metadata.plist

    # Bare ~/Library/* TCC dirs.
    ${homeDir}/Library/Accounts
    ${homeDir}/Library/AppleMediaServices
    ${homeDir}/Library/Assistant
    ${homeDir}/Library/Autosave Information
    ${homeDir}/Library/Biome
    ${homeDir}/Library/ContainerManager
    ${homeDir}/Library/Cookies
    ${homeDir}/Library/CoreFollowUp
    ${homeDir}/Library/Daemon Containers
    ${homeDir}/Library/DoNotDisturb
    ${homeDir}/Library/DuetExpertCenter
    ${homeDir}/Library/HomeKit
    ${homeDir}/Library/IdentityServices
    ${homeDir}/Library/IntelligencePlatform
    ${homeDir}/Library/Mail
    ${homeDir}/Library/Messages
    ${homeDir}/Library/Metadata/CoreSpotlight
    ${homeDir}/Library/Mobile Documents
    ${homeDir}/Library/PersonalizationPortrait
    ${homeDir}/Library/Safari
    ${homeDir}/Library/Sharing
    ${homeDir}/Library/Shortcuts
    ${homeDir}/Library/StatusKit
    ${homeDir}/Library/Suggestions
    ${homeDir}/Library/Trial
    ${homeDir}/Library/Weather
    ${homeDir}/Library/com.apple.aiml.instrumentation

    # ~/Library/Application Support/* TCC dirs.
    ${homeDir}/Library/Application Support/AddressBook
    ${homeDir}/Library/Application Support/CallHistoryDB
    ${homeDir}/Library/Application Support/CallHistoryTransactions
    ${homeDir}/Library/Application Support/CloudDocs
    ${homeDir}/Library/Application Support/com.apple.avfoundation
    ${homeDir}/Library/Application Support/com.apple.sharedfilelist
    ${homeDir}/Library/Application Support/com.apple.TCC
    ${homeDir}/Library/Application Support/DifferentialPrivacy
    ${homeDir}/Library/Application Support/FaceTime
    ${homeDir}/Library/Application Support/FileProvider
    ${homeDir}/Library/Application Support/Knowledge

    # Group Containers — broaden beyond `group.com.apple.*` to cover the
    # bare `com.apple.*` ones (bird/Home/MailPersonaStorage/etc.) that
    # also fail with FDA-required.
    ${homeDir}/Library/Group Containers/group.com.apple.*
    ${homeDir}/Library/Group Containers/com.apple.bird
    ${homeDir}/Library/Group Containers/com.apple.Home.group
    ${homeDir}/Library/Group Containers/com.apple.MailPersonaStorage
    ${homeDir}/Library/Group Containers/com.apple.PreviewLegacySignaturesConversion
    ${homeDir}/Library/Group Containers/com.apple.stickersd.group
    ${homeDir}/Library/Group Containers/com.apple.systempreferences.cache

    # Preferences plists for TCC-protected services. The plists exist
    # under ~/Library/Preferences but reading them requires FDA.
    ${homeDir}/Library/Preferences/com.apple.AddressBook.plist
    ${homeDir}/Library/Preferences/com.apple.homed.notbackedup.plist
    ${homeDir}/Library/Preferences/com.apple.homed.plist
    ${homeDir}/Library/Preferences/com.apple.madrid.plist
    ${homeDir}/Library/Preferences/com.apple.MobileSMS.plist

    # Package manager / build caches
    ${homeDir}/.cargo/registry
    ${homeDir}/.local/state/cabal
    ${homeDir}/.local/state/nix
    ${homeDir}/.npm
    ${homeDir}/go/pkg
    ${homeDir}/Library/pnpm
    ${homeDir}/Library/Python
    ${homeDir}/.swiftpm

    # IDE data
    ${homeDir}/.cursor-server

    # This program's own --verbose=2 transcripts: ~220 MB per run, a fresh
    # file every day, and worthless in a restore. The JSON manifests next to
    # them are 70 KB and are kept — they are the evidence for what each run
    # verified.
    ${logDir}/backup-home-*.log

    # Build artifacts (match anywhere in tree)
    node_modules
    target/debug
    target/release
    .direnv
    __pycache__
    *.pyc
    *.o

    # Nix build outputs (match anywhere)
    result

    # Re-downloadable games
    ${homeDir}/Games/GOG
  '' + lib.optionalString (cfg.extraExcludes != [ ]) ''

    # User-supplied excludes
    ${lib.concatStringsSep "\n" cfg.extraExcludes}
  '');

  # PATH for the program and everything it spawns: rust-script's toolchain
  # (cargo/rustc/cc compile the script on first run), restic and its
  # transport helpers (rclone for rclone:, ssh for sftp:), gnupg for the
  # typical passwordCommand surface (passveil, pass, `gpg --decrypt`).
  runtimePath = lib.makeBinPath ([
    pkgs.rust-script
    pkgs.cargo
    pkgs.rustc
    pkgs.stdenv.cc
    pkgs.stdenv.cc.bintools
    pkgs.restic
    pkgs.rclone
    pkgs.openssh
    pkgs.gnupg
    pkgs.coreutils
    pkgs.bash
  ] ++ cfg.extraRuntimeInputs);

  configJson = builtins.toJSON {
    home = homeDir;
    repo = cfg.repo;
    password_command = cfg.passwordCommand;
    exclude_file = "${excludeFile}";
    replica_repos = cfg.replicaRepos;
    retention = {
      inherit (cfg.retention) daily weekly monthly yearly;
    };
    verification = {
      enable = cfg.verification.enable;
      sample_size = cfg.verification.sampleSize;
    };
    log_dir = logDir;
    log_retention_days = cfg.logRetentionDays;
    status_file = cfg.statusFile;
    restic_bin = "${pkgs.restic}/bin/restic";
  };

  # The operational program: generic rust-script source with one embedded
  # config placeholder. Nix substitutes the serialized configuration and
  # pins the interpreter, so the store file is directly executable and all
  # operational behavior stays in Rust — no wrapper shell script.
  backupHomeScript = pkgs.writeTextFile {
    name = "backup-home.rs";
    executable = true;
    text = builtins.replaceStrings
      [ "#!/usr/bin/env rust-script" "@BACKUP_HOME_CONFIG_JSON@" ]
      [ "#!${pkgs.rust-script}/bin/rust-script" configJson ]
      (builtins.readFile ../backup-home.rs);
  };

  # Compiled exec-wrapper (no shell): pins PATH plus the darwin toolchain
  # environment cargo/rustc need when rust-script compiles the program on
  # first run, then execs the script. Same pattern as wallstats' rust-script
  # runtime. Works identically from the scheduler and an interactive shell.
  wrapperSource = pkgs.writeText "backup-home-wrapper.c" ''
    #include <errno.h>
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <unistd.h>

    struct environment_entry {
        const char *name;
        const char *value;
    };

    int main(int argc, char **argv) {
        (void)argc;

        static const char script[] = "${backupHomeScript}";
        static const struct environment_entry environment[] = {
            { "PATH", "${runtimePath}:/usr/bin:/bin:/usr/sbin:/sbin" },
            { "SHELL", "${pkgs.bash}/bin/bash" },
            { "CARGO", "${pkgs.cargo}/bin/cargo" },
            { "RUSTC", "${pkgs.rustc}/bin/rustc" },
            { "RUSTDOC", "${pkgs.rustc}/bin/rustdoc" },
            { "CC", "${pkgs.stdenv.cc}/bin/cc" },
            { "CXX", "${pkgs.stdenv.cc}/bin/c++" },
            { "AR", "${pkgs.stdenv.cc.bintools}/bin/ar" },
            { "RANLIB", "${pkgs.stdenv.cc.bintools}/bin/ranlib" },
            { "LIBRARY_PATH", "${pkgs.libiconv}/lib" },
            { "NIX_LDFLAGS", "-L${pkgs.libiconv}/lib" },
            { "CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER", "${pkgs.stdenv.cc}/bin/cc" },
            { "CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER", "${pkgs.stdenv.cc}/bin/cc" },
            { "SSL_CERT_FILE", "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt" },
            { "CARGO_HTTP_CAINFO", "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt" },
        };

        for (size_t index = 0; index < sizeof(environment) / sizeof(environment[0]); index++) {
            if (setenv(environment[index].name, environment[index].value, 1) != 0) {
                fprintf(stderr, "backup-home: cannot set %s: %s\n",
                        environment[index].name, strerror(errno));
                return 126;
            }
        }

        execv(script, argv);
        const int error = errno;
        fprintf(stderr, "backup-home: cannot execute %s: %s\n", script, strerror(error));
        return error == ENOENT ? 127 : 126;
    }
  '';

  backupHome = pkgs.runCommandCC "backup-home" { } ''
    mkdir -p "$out/bin"
    "$CC" -O2 -Wall -Wextra -Werror ${wrapperSource} -o "$out/bin/backup-home"
  '';

  useSysteml =
    if cfg.useSysteml == null
    then config.systeml.enable or false
    else cfg.useSysteml;

  onCalendar = lib.concatStringsSep ":" [
    "*-*-* ${lib.fixedWidthString 2 "0" (toString cfg.schedule.hour)}"
    (lib.fixedWidthString 2 "0" (toString cfg.schedule.minute))
    "00"
  ];
in
{
  options.services.backup-home = {
    enable = lib.mkEnableOption "Daily restic-based backup of the user's home directory.";

    repo = lib.mkOption {
      type = lib.types.str;
      example = "rclone:gdrive:backups/myhost";
      description = ''
        Restic repository URL. Anything `restic` understands works
        (`rclone:remote:path`, `s3:...`, `b2:...`, a local path, etc.).
        Strongly recommend a per-host path so multiple machines don't
        stomp each other.
      '';
    };

    passwordCommand = lib.mkOption {
      type = lib.types.str;
      example = lib.literalExpression ''"''${pkgs.passveil}/bin/passveil show restic/backup"'';
      description = ''
        Shell command that prints the restic repository password to
        stdout. Set as `RESTIC_PASSWORD_COMMAND`; also used for every
        replica repository. Use a secret-store wrapper (passveil, pass,
        age, …) — never an inline plaintext password.
      '';
    };

    replicaRepos = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "sftp:zh6433@zh6433.rsync.net:backups/myhost" ];
      description = ''
        Restic repository URLs the new snapshot is copied to on every run
        (`restic copy` — no second filesystem scan). Replicas share the
        primary's passwordCommand, are auto-initialized with
        `--copy-chunker-params` on first contact (bootstrapping all
        retained home snapshots), and get the same retention policy.
        `sftp:` replicas must be reachable with key-only (BatchMode) SSH,
        or every scheduled run will hang or fail.
      '';
    };

    verification = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Retrieval verification around every run: uniformly sample
          `sampleSize` regular files from the latest snapshot and
          restore them with `--verify` before the backup; re-restore the
          same sample after backup + prune and compare SHA-256/size
          manifests byte-for-byte; restore a fresh disjoint sample from
          the new snapshot; and run the equivalent check against every
          replica. A failed pre-check never blocks the backup itself —
          it is reported through the final exit status.
        '';
      };
      sampleSize = lib.mkOption {
        type = lib.types.addCheck lib.types.int (n: n >= 300) // {
          description = "integer of at least 300";
        };
        default = 300;
        description = ''
          Files per verification sample. Sampling 300 files without
          replacement gives at least `1 - 0.99^300 = 95.1%` probability
          of hitting a bad file when 1% or more of the snapshot's
          regular files are unretrievable. If the snapshot has fewer
          eligible files, all of them are tested. Values below 300 are
          rejected.
        '';
      };
    };

    extraExcludes = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "\${homeDir}/Mirrors/Computers" ];
      description = ''
        Additional patterns appended to the bundled macOS-junk exclude
        list. Each entry is a single line of restic exclude syntax.
      '';
    };

    extraRuntimeInputs = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = lib.literalExpression "[ pkgs.age pkgs.passveil ]";
      description = ''
        Extra packages prepended to the program's pinned PATH. Useful
        when the configured `passwordCommand` needs tools beyond the
        default set (restic, rclone, openssh, coreutils, gnupg, and the
        rust-script toolchain).
      '';
    };

    logRetentionDays = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 30;
      description = ''
        Delete `backup-home-*` logs and manifests older than this many days
        at the start of every run. `--verbose=2` writes roughly one line per
        file in `$HOME`, so an unpruned log directory grows by a couple of
        hundred megabytes a day. 0 keeps everything forever.
      '';
    };

    statusFile = lib.mkOption {
      type = lib.types.str;
      default = "${homeDir}/.local/state/backup-home/status.json";
      description = ''
        Small JSON document rewritten at the start and end of every run,
        holding the backup and recovery outcomes separately along with the
        timestamp each half last succeeded. Meant for desktop monitors, which
        would otherwise have to grep a multi-hundred-megabyte log. Set to the
        empty string to disable.
      '';
    };

    schedule = {
      hour = lib.mkOption {
        type = lib.types.ints.between 0 23;
        default = 14;
        description = "Hour of day (0–23) to run the backup.";
      };
      minute = lib.mkOption {
        type = lib.types.ints.between 0 59;
        default = 0;
        description = "Minute of hour (0–59) to run the backup.";
      };
    };

    retention = {
      daily   = lib.mkOption { type = lib.types.ints.unsigned; default =  7; };
      weekly  = lib.mkOption { type = lib.types.ints.unsigned; default =  4; };
      monthly = lib.mkOption { type = lib.types.ints.unsigned; default = 12; };
      yearly  = lib.mkOption { type = lib.types.ints.unsigned; default =  3; };
    };

    useSysteml = lib.mkOption {
      type = lib.types.nullOr lib.types.bool;
      default = null;
      description = ''
        Force the scheduling backend.

        - `null` (default): pick automatically — systemd user units when
          `config.systeml.enable` is true, launchd otherwise.
        - `true`: always emit systemd user units (requires systeml or a
          real systemd).
        - `false`: always emit a launchd agent.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      description = ''
        The `backup-home` program as a derivation: the compiled
        exec-wrapper around the configured rust-script.
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      services.backup-home.package = backupHome;

      home.packages = [
        pkgs.rclone
        pkgs.restic
        backupHome
      ];
    }

    (lib.mkIf useSysteml {
      systemd.user.services.backup-home = {
        Unit = {
          Description = "Daily home directory backup (restic + rclone, verified)";
        };
        Service = {
          Type = "oneshot";
          ExecStart = "${backupHome}/bin/backup-home";
          # systeml on macOS inherits launchd's minimal env. Set HOME so
          # rclone can find ~/.config/rclone/rclone.conf and rust-script
          # can keep its build cache; the wrapper pins PATH itself, the
          # base PATH here only covers pre-exec resolution.
          Environment = [
            "HOME=${homeDir}"
            "PATH=/usr/bin:/bin:/usr/sbin:/sbin"
          ];
          # Explicit "journal" — systeml only enables stdio capture for
          # units that say so by name (no implicit default).
          StandardOutput = "journal";
          StandardError  = "journal";
        };
      };
      systemd.user.timers.backup-home = {
        Unit = {
          Description = "Daily home backup at ${onCalendar}";
        };
        Timer = {
          OnCalendar = onCalendar;
          Persistent = true;
          Unit       = "backup-home.service";
        };
        Install.WantedBy = [ "timers.target" ];
      };
    })

    (lib.mkIf (!useSysteml) {
      launchd.agents.backup-home = {
        enable = true;
        config = {
          ProgramArguments = [ "${backupHome}/bin/backup-home" ];
          StartCalendarInterval = [{
            Hour   = cfg.schedule.hour;
            Minute = cfg.schedule.minute;
          }];
          EnvironmentVariables = {
            HOME = homeDir;
          };
          StandardOutPath  = "${homeDir}/.local/log/backup-home-launchd.stdout.log";
          StandardErrorPath = "${homeDir}/.local/log/backup-home-launchd.stderr.log";
        };
      };
    })
  ]);
}
